zuul:
  routes:
    grafana:
      sensitiveHeaders: Authorization
      path: /grafana/**
      url: http://${GRAFANA_HOST:localhost}:3000
    oauth:
      sensitiveHeaders: Cookie, Set-Cookie
      path: /authorization/**
      url: http://${AUTHORIZATION_SERVER_HOST:localhost}:8081
    authentication:
      path: /authentication/**
      url: http://localhost:8082

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgIK2Wt4x2EtDl41C7vfp
          OsMquZMyOyteO2RsVeMLF/hXIeYvicKr0SQzVkodHEBCMiGXQDz5prijTq3RHPy2
          /5WJBCYq7yHgTLvspMy6sivXN7NdYE7I5pXo/KHk4nz+Fa6P3L8+L90E/3qwf6j3
          DKWnAgJFRY8AbSYXt1d5ELiIG1/gEqzC0fZmNhhfrBtxwWXrlpUDT0Kfvf0QVmPR
          xxCLXT+tEe1seWGEqeOLL5vXRLqmzZcBe1RZ9kQQm43+a9Qn5icSRnDfTAesQ3Cr
          lAWJKl2kcWU1HwJqw+dZRSZ1X4kEXNMyzPdPBbGmU6MHdhpywI7SKZT7mX4BDnUK
          eQIDAQAB
          -----END PUBLIC KEY-----